baseURL = "https://blog.csrgo.com/"
languageCode = "en-us"
title = "CSRGO Blog"

[params]
  description = "Uncover AI Tools, Dev Roadmaps & Cutting-Edge Tech"
  author = "CSRGO"
  github = "https://github.com/csrgo"
  linkedin = "https://linkedin.com/in/csrgo"
  twitter = "https://twitter.com/csrgo"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "All Posts"
    url = "/posts/"
    weight = 2

[markup]
  [markup.highlight]
    style = "github-dark"
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    tabWidth = 4
    guessSyntax = true

[taxonomies]
  tag = "tags"
  category = "categories" 