backend:
  name: github
  repo: srikanth1815101/blog
  branch: main
  
local_backend: true

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "CSRGO" }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false }
      - { label: "Reading Time (minutes)", name: "readingTime", widget: "number", default: 5 }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" } 
